<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Store_loginData</name>
   <tag></tag>
   <elementGuidId>c59d7c47-e164-40e3-8be9-7fef41fedde2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept_gdpr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept_gdpr</value>
      <webElementGuid>ef31f436-b655-4be5-aa7c-732567ba5e8f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
