<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_linkedin_HomepageFooter</name>
   <tag></tag>
   <elementGuidId>9fbca9ed-466d-47a5-af06-1f348ef8f17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='https://www.linkedin.com/company/hancocks-confectionery?trk=top_nav_home']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
